name: communication-scaffold # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Oodles Messenger.
description: |
  Communication Scaffold is a WebRTC based set of APIs which offer a simple and easy plug-and-play kind of architecture. If you are in need of a tool that can be used within your organization for collaboration among employees, then you are at the right place. These APIs can be quickly integrated with your existing dashboard.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: static # use 'strict' once you have the right plugs and slots
icon: snap/gui/logo.png
parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: nil
